Don't pollute structs when trying to merge invalid keys
planswell/kitchen-sink pull request #39
Opened 2016-12-06 22:13 UTC by mariusbutuc

As part of [ch1263](https://app.clubhouse.io/planswell/story/1263/clean-up-year-1-values), we want to ensure we can't merge invalid keys into a struct.

Paired on this with @olafura, so @kenips & @boxxxie please have a 👀 .

2016-12-06 22:40 UTC, robertpeacock22 requested changes

2016-12-06 22:40 UTC, robertpeacock22 commented on lib/kitchen_sink/map.ex
> +  defp do_deep_merge(%{__struct__: _} = left, right) do
Comments please 📃

2016-12-07 01:07 UTC, boxxxie reviewed
I don't even know if it makes sense to do deep merge with structs

2016-12-07 14:46 UTC, mariusbutuc commented
@boxxxie Can you elaborate on this please?

2016-12-07 15:08 UTC, boxxxie commented
well, a struct has a lot of restrictions when it is merged

2016-12-07 15:09 UTC, boxxxie approved these changes

2016-12-07 15:10 UTC, merged