Handle unused variable warning
planswell/kitchen-sink pull request #42
Opened 2016-12-07 20:09 UTC by mariusbutuc

2016-12-08 16:45 UTC, xorgy requested changes

2016-12-08 16:45 UTC, xorgy commented on lib/kitchen_sink/map.ex
> +  defp do_key_paths({key, %{__struct__: _} = _value}) do
Perhaps `_value` doesn't need to be named at all. ;- )

2016-12-08 16:50 UTC, mariusbutuc commented on lib/kitchen_sink/map.ex
> +  defp do_key_paths({key, %{__struct__: _} = _value}) do
Touché!

2016-12-08 18:31 UTC, xorgy approved these changes
👌

2016-12-08 19:41 UTC, robertpeacock22 approved these changes

2016-12-09 16:27 UTC, boxxxie approved these changes

2016-12-09 16:28 UTC, merged