Add more tests
planswell/kitchen-sink pull request #51
Opened 2017-02-13 19:04 UTC by robertpeacock22

Add a guard against accepting 0 for the second parameter of ceil/2.

2017-02-13 19:06 UTC, olafura approved these changes

2017-02-13 19:55 UTC, mariusbutuc approved these changes

2017-02-13 22:02 UTC, xorgy approved these changes

2017-04-19 15:22 UTC, boxxxie commented on lib/kitchen_sink/math.ex
> +  def ceil(_, 0) do
the idea of significance seems non-standard
https://en.wikipedia.org/wiki/Floor_and_ceiling_functions

probably should rename this function

2017-04-19 15:25 UTC, boxxxie requested changes

2017-04-19 15:25 UTC, boxxxie commented on lib/kitchen_sink/math.ex
> +  def ceil(_, 0) do
maybe we should have a default value for significance that makes this look like the standard ceil function

2017-04-19 18:39 UTC, boxxxie approved these changes

2017-04-19 18:39 UTC, boxxxie commented on lib/kitchen_sink/math.ex
> +  iex> round_up_to_multiple(31, 5)
we will have to rename where this is used (pw-server)

2017-04-19 18:44 UTC, merged