Enhance map rename key
planswell/kitchen-sink pull request #53
Opened 2017-04-18 16:15 UTC by boxxxie

2017-04-18 17:32 UTC, olafura requested changes
Maybe do this with a option?

2017-04-19 13:56 UTC, olafura approved these changes

2017-04-19 14:00 UTC, olafura requested changes

2017-04-19 14:00 UTC, olafura commented on lib/kitchen_sink/map.ex
> +      {nil, false} -> map
Maybe use do `{nil, check} is_boolean(check) -> map`

2017-04-19 14:06 UTC, boxxxie commented on lib/kitchen_sink/map.ex
> +      {nil, false} -> map
probably faster not to do that

2017-04-19 14:07 UTC, boxxxie commented on lib/kitchen_sink/map.ex
> +      {nil, false} -> map
fixed

2017-04-19 14:11 UTC, olafura approved these changes

2017-04-19 14:33 UTC, robertpeacock22 requested changes
I would love to see a test for the case where `overwrite: false`

2017-04-19 14:39 UTC, robertpeacock22 approved these changes

2017-04-19 15:10 UTC, merged