Transpose juxt identity compose pipe
planswell/kitchen-sink pull request #6
Opened 2016-10-22 23:46 UTC by boxxxie

2016-10-23 21:53 UTC, kenips requested changes

2016-10-23 21:53 UTC, kenips commented on lib/kitchensink/function.ex
> +  end
How about:
```
def compose(functions) when is_list(functions) do
  functions
  |> Enum.reverse()
  |> pipe()
end
```

2016-10-23 21:53 UTC, kenips commented on lib/kitchensink/function.ex
> +  def compose(functions) when is_list(functions) do
Need some @doc

2016-10-23 21:53 UTC, kenips commented on lib/kitchensink/function.ex
> +  def pipe(functions) when is_list(functions) do
@doc

2016-10-23 21:53 UTC, kenips commented on test/kitchensink_test/function_test.exs
> +    assert F.compose([square, double, triple]).(3) == 3 * 3 * 2 * 18
How about `assert F.compose([square, double, triple]).(3) == :math.pow(3 * 3 * 2, 2)`

2016-10-23 22:16 UTC, boxxxie commented on lib/kitchensink/function.ex
> +  end
I made pipe after. I'll change this.

2016-10-24 15:57 UTC, kenips requested changes

2016-10-24 15:57 UTC, kenips commented on lib/kitchensink/list.ex
> +  def index_on(list_of_maps, take_keys, value_key) do
not sure about `index_on`. Maybe `to_lookup` is better?

2016-10-24 15:57 UTC, kenips commented on test/kitchensink_test/list_test.exs
> +      input =
tab!

2016-10-24 15:57 UTC, kenips commented on lib/kitchensink/list.ex
> +  def index_on(list_of_maps, take_keys, value_key) do
How about adding support for `take_keys` to be one to many.

2016-10-24 16:00 UTC, boxxxie commented on lib/kitchensink/list.ex
> +  def index_on(list_of_maps, take_keys, value_key) do
name inspired by underscore

2016-10-24 16:01 UTC, boxxxie commented on lib/kitchensink/list.ex
> +  def index_on(list_of_maps, take_keys, value_key) do
which is indexBy

2016-10-24 16:02 UTC, boxxxie commented on lib/kitchensink/list.ex
> +  def index_on(list_of_maps, take_keys, value_key) do
i think that to_... sounds like it's converting to a proper data structure... this is a generic map. i would like a better name.

2016-10-24 16:02 UTC, kenips commented on lib/kitchensink/list.ex
> +  def index_on(list_of_maps, take_keys, value_key) do
index by then.

2016-10-24 16:04 UTC, kenips approved these changes

2016-10-24 16:10 UTC, merged