Add KitchenSink.Algorithms.binary_search & tests
planswell/kitchen-sink pull request #62
Opened 2017-06-13 18:47 UTC by mikestok

The ability to use a "special" calculation for mid point is for @maedhr .

## Changes since 1.0.2

  * Added CHANGELOG.md
  * Added KitchenSink.Algorithms
    * binary_search/{2,3,4}
  * Updated credo 0.6.1 → 0.8.1
  * Updated dialyxir 0.4.4 → 0.5.0
  * Updated ex_doc 0.14.5 → 0.16.1

2017-06-13 18:55 UTC, boxxxie approved these changes

2017-06-13 19:39 UTC, maedhr approved these changes

2017-06-13 20:10 UTC, olafura requested changes
Rename the function to match behaviour. Also have the lookup function with two params ;)

2017-06-13 21:50 UTC, mikestok commented on lib/kitchen_sink/algorithms.ex
> +  end
Is there a way to default that last argument "nicely"?

2017-06-13 22:23 UTC, olafura commented on lib/kitchen_sink/algorithms.ex
> +  end
def binary_search(start .. finish, fit \\ &binary_search_midpoint/2)

2017-06-14 14:15 UTC, olafura approved these changes

2017-06-14 14:22 UTC, merged