Add a function to ensure an integer is returned
planswell/kitchen-sink pull request #63
Opened 2017-07-27 18:34 UTC by olafura

Sometimes we have to make sure we are getting integers even if
the source is a string so this function helps with that

2017-07-27 18:36 UTC, enricribas approved these changes

2017-07-27 18:38 UTC, Corvillus approved these changes

2017-07-27 18:41 UTC, mariusbutuc commented on lib/kitchen_sink/integer.ex
> +  def ensure_integer(i) when is_integer(i), do: i
`Integer.ensure_integer/1` might be a bit much. 

Naming is hard; some raw thoughts would be naming the module `Convert` or `Cast` and the function `to_integer` or something along those lines?

2017-07-27 18:50 UTC, olafura commented on lib/kitchen_sink/integer.ex
> +  def ensure_integer(i) when is_integer(i), do: i
Then I would be tempted to use Protocols :D

2017-07-27 18:53 UTC, olafura commented on lib/kitchen_sink/integer.ex
> +  def ensure_integer(i) when is_integer(i), do: i
There is also https://github.com/DanielZendejas/lazy_integer

2017-07-27 21:20 UTC, mariusbutuc commented on lib/kitchen_sink/integer.ex
> +  def ensure_integer(i) when is_integer(i), do: i
Nice idea behind `LazyInteger`! At a quick glance @olafura, it seems to be Ecto-specific…

2017-07-28 13:26 UTC, mariusbutuc commented on lib/kitchen_sink/integer.ex
> +  def ensure_integer(i) when is_integer(i), do: i
@olafura on a second glance, we also have `Bolean`, `Map` etc. so `Integer` makes sense in this context.

`Integer.cast/1` could be an option too, but don't have a strong feeling about it. :shipit:

2017-07-28 13:26 UTC, mariusbutuc approved these changes

2017-08-22 20:41 UTC, maedhr approved these changes

2017-08-22 20:41 UTC, maedhr commented on lib/kitchen_sink/integer.ex
> +  def ensure_integer(s) when is_binary(s), do: String.to_integer(s)
Should we trim the string so it doesn't blow up?

2017-08-22 20:47 UTC, maedhr requested changes
I meant to not approve last time... I will one-day learn to github.

2017-08-22 20:47 UTC, olafura commented
:)

2017-08-24 13:55 UTC, mariusbutuc commented on lib/kitchen_sink/integer.ex
> +  def ensure_integer(s) when is_binary(s), do: String.to_integer(s)
```elixir
def ensure_integer(s) when is_binary(s), do: s |> String.strip() |> String.to_integer()
```

2017-08-28 16:56 UTC, maedhr approved these changes

2017-08-28 16:58 UTC, merged