Fix Struct.to_map for list of primitives.
planswell/kitchen-sink pull request #64
Opened 2017-08-16 18:00 UTC by Corvillus

2017-08-16 19:57 UTC, olafura requested changes

2017-08-16 19:57 UTC, olafura commented on test/kitchen_sink/struct_test.exs
> +          age: nil,
It should be empty

2017-08-16 20:33 UTC, olafura approved these changes

2017-08-17 15:28 UTC, mariusbutuc commented on test/kitchen_sink/struct_test.exs
> +          age: nil,
@Corvillus & @olafura was there a decision around this, one that was maybe made in a live chat?

2017-08-17 15:28 UTC, olafura commented on test/kitchen_sink/struct_test.exs
> +          age: nil,
I'm going to write a separate PR ;)

2017-08-22 20:26 UTC, robertpeacock22 approved these changes

2017-08-22 20:28 UTC, merged