Add drop option to Struct.to_map()
planswell/kitchen-sink pull request #67
Opened 2017-08-24 18:16 UTC by Corvillus

Adds ability to drop keys (like say, Ecto's often unwanted __meta__ keys) recursively from the struct in the conversion process.

2017-08-24 18:17 UTC, olafura approved these changes

2017-08-24 22:08 UTC, mariusbutuc requested changes

2017-08-24 22:08 UTC, mariusbutuc commented on test/test_helper.exs
> +# IEx.break!(KitchenSink.Struct, :do_deep_struct_to_map, 3, 10)
Is this needed?

2017-08-25 14:04 UTC, mariusbutuc approved these changes

2017-08-25 19:46 UTC, maedhr approved these changes

2017-08-25 20:19 UTC, merged